한승준/Congraduate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

한승준/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

한승준/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
]

한승준/accounts/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

한승준/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
  title = models.CharField(max_length=100)
  created_at = models.DateTimeField(auto_now_add=True)

한승준/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):

  class Meta(UserCreationForm.Meta):
    model = get_user_model()

class CustomUserChangeForm(UserChangeForm):

  class Meta(UserChangeForm.Meta):
    model = get_user_model()
    fields = '__all__'

한승준/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm 

@require_http_methods(['GET', 'POST'])
def login(request):
  if request.user.is_authenticated:
    return redirect('articles:index')
  if request.method == 'POST':
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
      auth_login(request, form.get_user())
      return redirect('articles:index')
  else:
    form = AuthenticationForm()
  context = {
    'form': form
  }
  return render(request, 'accounts/login.html', context)

@require_POST
def logout(request):
  if request.method == 'POST':
    print(request)
    auth_logout(request)
    return redirect('articles:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
  if request.method == 'POST':
    form = CustomUserCreationForm(data=request.POST)
    if form.is_valid():
      user = form.save()
      # 바로 로그인
      auth_login(request, user)
      return redirect('articles:index')
  else:
    form = CustomUserCreationForm()
  context = {
    'form': form,
  }
  return render(request, 'accounts/signup.html', context)

def delete(request):
    if request.method == 'POST':
      request.user.delete()
      auth_logout(request)
    return redirect('articles:index')

@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
      form = CustomUserChangeForm(request.POST, instance=request.user)
      if form.is_valid():
        form.save()
        return redirect('articles:index')
    else:
      form = CustomUserChangeForm(instance=request.user)
    context = {
      'form':form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
      form = PasswordChangeForm(request.user, data=request.POST)
      if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        return redirect('articles:index')
    else:
      form = PasswordChangeForm(request.user)
    context = {
      'form':form
    }
    return render(request, 'accounts/change_password.html', context)

한승준/articles/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.
def index(request):
  articles = Article.objects.all()
  context = {
    'articles':articles,
  }
  return render(request, 'articles/index.html', context)

한승준/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change_password' %}" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value='확인'>
</form>
{% endblock content %}

한승준/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>로그인</h1>
<form action="{% url 'accounts:login' %}" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value='로그인'>
</form>
{% endblock content %}

한승준/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>회원가입</h1>
<form action="{% url 'accounts:signup' %}" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value='확인'>
</form>
{% endblock content %}

한승준/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>회원정보수정</h1>
<form action="{% url 'accounts:update' %}" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value='확인'>
</form>
{% endblock content %}

한승준/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Congraduate</h1>
{% if request.user.is_authenticated %}
  <a href="#">CREATE</a>
{% else %}
  <a href="#">새 글을 작성하려면 로그인하세요</a>
{% endif %}
{% endblock content %}

한승준/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <div class="container">
      {% if request.user.is_authenticated %}
        <h3>Hello, {{ user }}</h3>
        <form action="{% url 'accounts:logout' %}" method='POST'>
          {% csrf_token %}
          <input type="submit" value='로그아웃'>
        </form>
        <a href="{% url 'accounts:update' %}">회원정보수정</a>
        <form action="{% url 'accounts:delete' %}" method='POST'>
          {% csrf_token %}
          <input type="submit" value='회원탈퇴'>
        </form>
      {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
      {% endif %}
      <hr>
      {% block content %}
      {% endblock content %}
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>